version: '3.7'
services:

  node:
    build:
      context: ./frontend
      dockerfile: ./../deployment/node/Dockerfile
    restart: always
    ports:
      - '80:80'
      - '3000:3000'
    volumes:
      - ./frontend:/var/www/html

#  nginx:
#    container_name: nginx
#    build:
#      context: ./deployment/nginx
#      dockerfile: Dockerfile
#    restart: always
#    ports:
#      - '80:80'
#    depends_on:
#      - octane
#    volumes:
#      - ./app/public:/var/www/showcase/public
#
#  octane:
#    container_name: octane
#    build:
#      context: ./app
#      dockerfile: ./../deployment/octane/Dockerfile
#    restart: always
#    env_file:
#      - .env
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    working_dir: /var/www/showcase
#    volumes:
#      - ./app:/var/www/showcase
