version: '3.7'
services:

#  node:
#    build:
#      context: ./frontend
#      dockerfile: ./../deployment/node/Dockerfile
#    restart: always
#    ports:
#      - '80:80'
#      - '3000:3000'
#    volumes:
#      - ./frontend:/var/www/html

  nginx:
    container_name: nginx
    build:
      context: ./deployment/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:80'
    depends_on:
      - fpm
    volumes:
      - .:/var/www/uny

  fpm:
      container_name: fpm
      build:
          context: .
          dockerfile: ./deployment/fpm/Dockerfile
      restart: always
      env_file:
          - .env
      extra_hosts:
          - "host.docker.internal:host-gateway"
      working_dir: /var/www/uny
      volumes:
          - .:/var/www/uny

  mysql:
    image: mysql
    ports:
        - "3306:3306"
    volumes:
        - "./docker/mysql/database/:/var/lib/mysql"
    environment:
        MYSQL_DATABASE: "uny_db"
        MYSQL_USER: "uny_db"
        MYSQL_PASSWORD: "uny_db"
        MYSQL_ROOT_PASSWORD: "uny_db"
